name: Denylist Request
description: Report the domains that should be blocked.
labels: ["deny"]
assignees: 
  - hagezi
body:
  - type: dropdown
    id: blocklists
    attributes:
      label: Which blocklist(s) do you use?
      multiple: true
      options:
        - Multi LIGHT
        - Multi NORMAL
        - Multi PRO
        - Multi PRO mini
        - Multi PRO++
        - Multi PRO++ mini
        - Multi ULTIMATE
        - Multi ULTIMATE mini
        - Fake
        - Pop-Up Ads
        - Threat Intelligence Feeds
        - Threat Intelligence Feeds medium
        - Threat Intelligence Feeds mini
        - Threat Intelligence Feeds IPs
        - DoH/VPN/TOR/Proxy Bypass
        - DoH Bypass
        - DoH Bypass IPs
        - Safesearch not supported
        - Dynamic DNS
        - Badware Hoster
        - Most Abused TLDs
        - Anti Piracy
        - Gambling
        - Native Tracker
        - Allowlist Referral
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Which category do the domain(s) to be blocked belong to?
      description: |
        Specify the categories to which the domains to be blocked belong. If it’s not listed, select Other and specify the category in the comments section below.
      multiple: true
      options:
        - Ads
        - Pop-Up Ads
        - Tracking
        - Bug/Error tracking
        - Analytics/Metrics/Telemetry
        - Malware/Badware/Phishing/Scam
        - Gambling
        - Piracy
        - DoH/VPN/TOR/Proxy DNS bypass 
        - Other
    validations:
      required: true
  - type: input
    id: other_category
    attributes:
      label: Other category
      description: |
        If you selected Other, please enter the category here.
    validations:
      required: false

  - type: textarea
    id: domains
    attributes:
      label: Which domain(s) should be blocked?
      description: |
        Provide the domains that should be blocked, ensuring you include only domain names (e.g., example.com). Do not include adblock rules, URLs, or other formats.
        IMPORTANT: No clickable links and ensure that you defang malicious domains, such as "malicious-domain[.]top," to safeguard against the potential ban of your GitHub account.
    validations:
      required: true

  - type: textarea
    id: source
    attributes:
      label: Which website or app accesses the domain(s)?
      description: |
        Specify the websites or apps through which the domains are accessed.
    validations:
      required: true
 
  - type: textarea
    id: reason
    attributes:
      label: Why should these domain(s) be blocked?
      description: |
        Clearly explain why each domain should be blocked, including details such as tracking behavior, malicious activity, or how the domain is accessed.
    validations:
      required: true
  
  - type: checkboxes
    id: blocked
    attributes:
      label: Confirmation
      options:
        - label: I have verified that no existing issue explains why the domain(s) were previously unblocked or why the blocking request was declined.
          required: true
        - label: I have verified that the domain(s) is/are not already blocked.
          required: true
        - label: I have verified that the domain(s) is/are active and not inactive (dead).
          required: true
        - label: I have provided sufficient details to justify the need for blocking the domain(s).
          required: true
  
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      options:
        - label: I confirm that the request does not contain any sexually explicit material or private/sensitive information.
          required: true
        - label: I confirm that the request does not contain any clickable links to malicious sites and that I have obfuscated malicious domains using defanging (e.g., malicious-domain[.]top).
          required: true
